### PR TITLE
Create setRole.js

### PR DESCRIPTION
**Pull request by Rakejs**
create $setRole functions
It has the same usage like $giveRole

### CODE REVIEW

**Comment by Rakejs** [comment]
add $math
Usage $math[operation] like $math[20+10]

**Comment by Rubenennj** [comment]
This was already added for next update, it supports multiple roles too.

**Review by Rakejs — COMMENTED** [review]
what about $math

**Comment by DevSpen** [comment]
ruben fr

**Comment by constalletion-2** [comment]
why not $djsEval '10' + '20' nya

**Comment by DevSpen** [comment]
Security issues. E.g if you do `$djsEval[message;$message]` then turn into a "math" command then anyone can use the eval. This is why the math function should be thing

**Comment by Rubenennj** [comment]
codes were wrong

**Comment by DevSpen** [comment]
L

**Pull request closed without merging**
