### PR TITLE
Create clientToken.js

### PR DESCRIPTION
**Pull request by DevSpen**

### CODE REVIEW

**Comment by AvonZzZ** [comment]
why? Just why? ._.

**Comment by DevSpen** [comment]
Why not 🥲😳

**Comment by AvonZzZ** [comment]
a) useless lmao
b) how would even be used?
c) useless 😃

**Comment by DevSpen** [comment]
Glad you like it! :D

**Comment by AvonZzZ** [comment]
i- kk nvm lmao

**Comment by DiscordBond** [comment]
Imagine endless empty circle because token is unknown… 
client.login('$clientToken')

**Comment by DevSpen** [comment]
Lmfao

**Comment by Rubenennj** [comment]
sus

**Comment by Rubenennj** [comment]
sus

**Pull request merged**
